nginx:
    build: ./nginx
    ports:
     - "80:80"
     - "443:443"
    volumes: 
     - /etc/nginx/psw:/etc/nginx/psw
     - /etc/nginx/ssl:/etc/nginx/ssl
    environment:
     - DOMAIN_NAME=robrett.com
mongo:
    image: mongo:3.0.2