nginx:
    build: ./nginx
    links: 
        - app1:app1
    ports:
        - "80:80"
app1:
    build: ./infographics-server
    links:
        - mongo
    ports:
        - "4500"
    volumes:
        - /tmp:/tmp
    environment:
        - ANGULAR_SRC=./../infographics-angular/dist/index.html
mongo:
    image: mongo:3.3
