mongo:
    image: mongo:3.3
    ports:
        - "27017:27017"

mongo-seed:
  build: ./mongo-seed
  links:
    - mongo
nginx:
    build: ./nginx
    links: 
        - app1:app1
    ports:
        - "80:80"
app1:
    build: ./infographics-server
    links:
        - mongo
    ports:
        - "4500"
    volumes:
        - /tmp:/tmp
    environment:
        - ANGULAR_SRC=./../infographics-angular/dist/index.html